vim.keymap.set({"n", "v"}, ";", "l", { noremap = true })
vim.keymap.set({"n", "v"}, "l", "k", { noremap = true })
vim.keymap.set({"n", "v"}, "k", "j", { noremap = true })
vim.keymap.set({"n", "v"}, "j", "h", { noremap = true })
vim.keymap.set({"n", "v"}, "<c-w>;", "<c-w>l", { noremap = true })
vim.keymap.set({"n", "v"}, "<c-w>l", "<c-w>k", { noremap = true })
vim.keymap.set({"n", "v"}, "<c-w>k", "<c-w>j", { noremap = true })
vim.keymap.set({"n", "v"}, "<c-w>j", "<c-w>h", { noremap = true })
vim.keymap.set({"n", "v"}, "<leader>i", "<c-^>", { noremap = true })
vim.keymap.set('n', '<leader>o', ":NERDTreeToggle<CR>", {})
vim.keymap.set("n", "gj", ":tabp<CR>", { noremap = true })
vim.keymap.set("n", "g;", ":tabn<CR>", { noremap = true })
vim.keymap.set("n", "gk", ":execute 'silent! tabmove ' . (tabpagenr()-2)<CR>", { noremap = true, silent = true })
vim.keymap.set("n", "gl", ":execute 'silent! tabmove ' . (tabpagenr()+1)<CR>", { noremap = true, silent = true })
vim.keymap.set("n", "gpe", ":lua vim.diagnostic.open_float()<CR>", { noremap = true, silent = true })